# Generated by Django 4.0.4 on 2022-05-17 18:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Case',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField()),
                ('detention_period', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Complain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('summary', models.TextField()),
                ('replied', models.BooleanField(default=False)),
                ('status', models.TextField(choices=[('1', 'Pending'), ('2', 'Replied')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Prisoner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Not_provided', max_length=30)),
                ('lastname', models.CharField(default='Not_provided', max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('identification', models.IntegerField()),
                ('phone', models.IntegerField()),
                ('status', models.CharField(choices=[('1', 'IN_MATE'), ('2', 'OUT_MATE')], max_length=10)),
                ('date', models.DateField()),
                ('gender', models.TextField(choices=[('1', 'IN_MATE'), ('2', 'OUT_MATE')], max_length=10)),
                ('address', models.CharField(max_length=20, null=True)),
                ('release_date', models.DateField()),
                ('photo', models.ImageField(default='avatar.png', upload_to='photos/')),
                ('case', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='prisoners_app.case')),
            ],
        ),
        migrations.CreateModel(
            name='Visitor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Not_provided', max_length=30)),
                ('lastname', models.CharField(default='Not_provided', max_length=30)),
                ('identification', models.IntegerField()),
                ('phone', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('relationship', models.CharField(choices=[('1', 'Parent'), ('2', 'Child'), ('3', 'Relative'), ('4', 'Friend')], max_length=10)),
                ('prisoner', models.ManyToManyField(to='prisoners_app.prisoner')),
                ('visitors', models.ManyToManyField(to='prisoners_app.visitor')),
            ],
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('where_from', models.TextField(max_length=50)),
                ('where_to', models.TextField(max_length=50)),
                ('reason', models.TextField()),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners_app.prisoner')),
            ],
        ),
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('summary', models.TextField()),
                ('complain', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='prisoners_app.complain')),
            ],
        ),
        migrations.CreateModel(
            name='Leave',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('reason', models.TextField()),
                ('approval', models.CharField(max_length=10)),
                ('status', models.CharField(choices=[('1', 'Active'), ('2', 'Expired')], max_length=10)),
                ('prisoner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners_app.prisoner')),
            ],
        ),
        migrations.AddField(
            model_name='complain',
            name='prisoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners_app.prisoner'),
        ),
    ]
