# Generated by Django 4.0.4 on 2022-05-02 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.CharField(choices=[('1', 'IN_MATE'), ('2', 'OUT_MATE')], max_length=10),
        ),
    ]
