# Generated by Django 4.0.4 on 2022-05-19 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.TextField(choices=[('1', 'Male'), ('2', 'Female')], max_length=10),
        ),
    ]
