# Generated by Django 4.0.4 on 2022-05-28 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0002_alter_prisoner_gender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transfer',
            name='where_from',
            field=models.TextField(choices=[('1', 'Karubanda Prison')], max_length=20),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='where_to',
            field=models.TextField(choices=[('1', 'Mageregere'), ('2', 'Muhanga prison'), ('3', 'Ririma prison'), ('4', 'Huye prison'), ('5', 'Nyagatare')], max_length=20),
        ),
        migrations.DeleteModel(
            name='Visit',
        ),
    ]
