# Generated by Django 4.0.4 on 2022-05-29 18:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0004_cell_rename_case_crime_rename_case_prisoner_crime_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prisoner',
            name='cell',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='prisoners_app.cell'),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='identification',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='phone',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='release_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
