# Generated by Django 4.0.4 on 2022-05-29 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0005_alter_prisoner_cell_alter_prisoner_identification_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='visitor',
            name='date',
            field=models.DateField(default='2020-5-20'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.CharField(blank=True, choices=[('1', 'INMATE'), ('2', 'OUTMATE')], default='INMATE', max_length=10),
        ),
    ]
