# Generated by Django 4.0.4 on 2022-05-30 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0007_alter_cell_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='cell',
            name='max_inmates',
            field=models.IntegerField(default=4),
        ),
    ]
