# Generated by Django 4.0.4 on 2022-05-31 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0009_alter_cell_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='status',
            field=models.CharField(blank=True, choices=[('Empty', 'Empty'), ('Visible', 'Visible'), ('Full', 'Full')], default='Empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='complain',
            name='status',
            field=models.TextField(choices=[('Pending', 'Pending'), ('Replied', 'Replied')], max_length=10),
        ),
        migrations.AlterField(
            model_name='leave',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active'), ('Expired', 'Expired')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='marital_status',
            field=models.TextField(choices=[('Single', 'Single'), ('Married', 'Married'), ('Divorced', 'Divorced')], max_length=10),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='status',
            field=models.CharField(blank=True, choices=[('INMATE', 'INMATE'), ('OUTMATE', 'OUTMATE')], default='INMATE', max_length=10),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='where_to',
            field=models.TextField(choices=[('Mageregere', 'Mageregere'), ('Muhanga prison', 'Muhanga prison'), ('Ririma prison', 'Ririma prison'), ('Huye prison', 'Huye prison'), ('Nyagatare prison', 'Nyagatare prison'), ('Kacyiru', 'Kacyiru'), ('Wawa', 'Wawa')], max_length=20),
        ),
    ]
