# Generated by Django 4.0.4 on 2022-05-31 18:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0010_alter_cell_status_alter_complain_status_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Release',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
            ],
        ),
        migrations.RemoveField(
            model_name='reply',
            name='complain',
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='phone',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name='Complain',
        ),
        migrations.DeleteModel(
            name='Reply',
        ),
        migrations.AddField(
            model_name='release',
            name='prisoner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='prisoners_app.prisoner'),
        ),
    ]
