# Generated by Django 4.0.4 on 2023-03-14 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0011_release_remove_reply_complain_alter_prisoner_email_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cell',
            name='status',
            field=models.CharField(blank=True, choices=[('Empty', 'Empty'), ('Contained', 'Contained'), ('Full', 'Full')], default='Empty', max_length=10),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='gender',
            field=models.TextField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
    ]
