# Generated by Django 4.0.4 on 2023-03-14 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0014_alter_complaint_date_alter_complaint_feedback'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, null=True),
        ),
    ]
