# Generated by Django 4.0.4 on 2023-03-15 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0015_alter_complaint_feedback'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='confirmation',
        ),
        migrations.AddField(
            model_name='complaint',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Approved'), ('Expired', 'Denied')], default='Pending', max_length=10),
        ),
    ]
