# Generated by Django 4.1.7 on 2023-03-18 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('prisoners_app', '0016_remove_complaint_confirmation_complaint_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='complaint',
            name='feedback',
            field=models.TextField(blank=True, default='Your complaints is still waiting approval'),
        ),
        migrations.AlterField(
            model_name='complaint',
            name='status',
            field=models.CharField(blank=True, choices=[('Pending', 'Pending'), ('Approved', 'Approved'), ('Denied', 'Denied')], default='Pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='prisoner',
            name='identification',
            field=models.IntegerField(max_length=16),
        ),
        migrations.AlterField(
            model_name='transfer',
            name='where_from',
            field=models.TextField(choices=[('Karubanda Prison', 'Karubanda Prison'), ('Congo Nile', 'Congo Nile')], max_length=20),
        ),
    ]
