# Generated by Django 4.0.4 on 2022-04-15 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts_app', '0002_rename_title_role_name_remove_category_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(default='noname', max_length=50),
        ),
        migrations.AlterField(
            model_name='employee',
            name='firstname',
            field=models.CharField(default='noname', max_length=30),
        ),
        migrations.AlterField(
            model_name='employee',
            name='lastname',
            field=models.CharField(default='noname', max_length=30),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(default='noname', max_length=50),
        ),
    ]
